# -------------------------------------NUMPY---------------------------------------------------------------

### Creating Numpy arrays

In [1]:
import numpy as np
a = np.array([[1, 3, 2], [4,5, 6], [7, 8, 9]])
print(a)

[[1 3 2]
 [4 5 6]
 [7 8 9]]


## Numpy arrays

In [2]:
import math
l = [1, 2, 3, 6, 5, 4]
l.sort()
print(len(l)//2)
np.square(l)

3


array([ 1,  4,  9, 16, 25, 36])

In [3]:
import numpy as np 
a = np.array([[1, 2, 3], [4,5, 6], [7, 8, 9]])
print(a)
print('Dimensions : ', a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions :  2


In [4]:
import numpy as np
import sys#sys module provides access to various system-specific parameters and functions.

array = np.array([12, 23, 45, 56])
list = [12, 23, 45, 56]
print(f'Size of l in bytes : ',sys.getsizeof(1)*len(l)) # (same)size*1en(l)
print(f'Size of a in bytes : ',a.size*a.itemsize) #no. of elements(size of array)* byte size of each element of the array

a = np.array([12, 23, 45, 56], dtype='float64')
print(a.size*a.itemsize) #difference between float bytesize and int bytesize

Size of l in bytes :  168
Size of a in bytes :  36
32


In [5]:
# preparing a 1d array from numpy
import numpy as np

a = np.array([(10, 9, 8, 7, 6),(5,4,3,2,1)])
print(a)

b = np.arange(5, 51, step=5)
b = b.reshape((2, 5))
print(b)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 5 10 15 20 25]
 [30 35 40 45 50]]


In [6]:
c = np.vstack((a, b))
print(c)
d = np.hstack((a, b))
print(d)

[[10  9  8  7  6]
 [ 5  4  3  2  1]
 [ 5 10 15 20 25]
 [30 35 40 45 50]]
[[10  9  8  7  6  5 10 15 20 25]
 [ 5  4  3  2  1 30 35 40 45 50]]


In [7]:
# 2d array
c = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(c)

d = np.arange(1,17).reshape(2, 8)
print(d)
type(d)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


numpy.ndarray

In [8]:
# arrays of zeros and ones , 3d array
c = np.zeros((3, 2))
print(c)
c = np.ones((3, 4))
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## adding arrays

In [9]:
p = np.array([1, 2, 3, 4, 5])
q = np.array([9, 8, 7, 6, 5])
print(np.sum((p, q), axis=0))  # axis=0 if you want to add numbers in a column ,
print(np.sum((p, q), axis=1))# axis = 1 if u want to sum the numbers inside the arrays and make it a single array
print(np.sum((p, q)))# dont use axis if u want to sum all the numbers in the array

[10 10 10 10 10]
[15 35]
50


## array slicing

In [10]:
a = np.array([22, 92, 34, 64, 15])
print(a)
print(a[np.argsort(a)[-2:]])
print(a[np.argsort(a)[-4:]]) # input the position and get the value of the reqd position

[22 92 34 64 15]
[64 92]
[22 34 64 92]


In [11]:
e = np.linspace(1, 50, 50)
e

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

## changing values

In [12]:
e[45:46]= 500
e

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45., 500.,  47.,  48.,  49.,  50.])

## copying array

In [13]:
f = e.copy()
f[49:]=10
f

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45., 500.,  47.,  48.,  49.,  10.])

## bool values

In [14]:
f == e

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

## replacing all the even numbers in the array

In [15]:
import numpy as np
arr = np.arange(1, 11)

arr[arr % 2 == 0] = -1
#Here we are divinding each of arr values by 2 and checking if their remainder is equal to zero
#if cond id true we place the val -1
print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9 -1]


## extracting common element from two arrays

In [16]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 87, 9, 0])
b = np.array([2, 4, 12, 34, 67, 87, 43, 21])

print(np.intersect1d(a, b))

[ 2  4 87]


## Pickling and unpickling

In [17]:
#Pickling
import pickle
 
data = [ { 'a':'A', 'b':2, 'c':3.0, 'd':4.5,  'e':5} ]
data_string = pickle.dumps(data)
print ('PICKLE:', data_string )

PICKLE: b'\x80\x04\x956\x00\x00\x00\x00\x00\x00\x00]\x94}\x94(\x8c\x01a\x94\x8c\x01A\x94\x8c\x01b\x94K\x02\x8c\x01c\x94G@\x08\x00\x00\x00\x00\x00\x00\x8c\x01d\x94G@\x12\x00\x00\x00\x00\x00\x00\x8c\x01e\x94K\x05ua.'


In [18]:
#Unpickling
data2 = pickle.loads(data_string)
print(data2)

[{'a': 'A', 'b': 2, 'c': 3.0, 'd': 4.5, 'e': 5}]
